---
title: "riak-cs fails to start after reimporting Docker container"
description: ""
project: community
lastmod: 2017-02-09T02:06:03-08:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg17943"
author_name: "Jean-Marc Le Roux"
project_section: "mailinglistitem"
sent_date: 2017-02-09T02:06:03-08:00
---


Hello,

here is the original github issue :

https://github.com/basho/riak\\_cs/issues/1329

I'm using riak-cs 2.1.1-1.el6 with stanchion 1.5.0-1.el6 on CentOS 6.8 in a
Docker container.
To make the data persistent, the following directories are mounted from
outside the container :

 - /var/log
 - /var/lib/riak/

Everything works fine except when I remove/reimport the container.
Even when it's the same container.
The riak data is here in /var/lib/riak (bitcask and leveldb stuff). ACLs
look fine on those files.

Riak starts. Stanchion starts. But riak-cs won't start.
With a riak-cs concole, it looks like the problem is here :

&gt; (riak-cs@127.0.0.1)1&gt; [os\\_mon] memory supervisor port (memsup): Erlang has 
&gt; closed
&gt;
&gt; =INFO REPORT==== 18-Jan-2017::09:38:31 ===
&gt; alarm\\_handler: {clear,system\\_memory\\_high\\_watermark}
&gt; [os\\_mon] cpu supervisor port (cpu\\_sup): Erlang has closed
&gt; {"Kernel pid 
&gt; terminated",application\\_controller,"{application\\_start\\_failure,riak\\_cs,{notfound,{riak\\_cs\\_app,start,[normal,[]]}}}"}
&gt;
&gt; var/log/riak-cs/access.log.2017\\_01\\_18\\_09 is empty.
Here is what /var/log/riak-cs/crash.log says:
&gt;
&gt; 2017-01-18 09:38:31 =CRASH REPORT====
&gt; crasher:
&gt; initial call: application\\_master:init/4
&gt; pid: &lt;0.148.0&gt;
&gt; registered\\_name: []
&gt; exception exit: 
&gt; {{notfound,{riak\\_cs\\_app,start,[normal,[]]}},[{application\\_master,init,4,[{file,"application\\_master.erl"},{line,133}]},{proc\\_lib,init\\_p\\_do\\_apply,3,[{file,"proc\\_lib.erl"},{line,239}]}]}
&gt; ancestors: [&lt;0.147.0&gt;]
&gt; messages: [{'EXIT',&lt;0.149.0&gt;,normal}]
&gt; links: [&lt;0.147.0&gt;,&lt;0.7.0&gt;]
&gt; dictionary: []
&gt; trap\\_exit: true
&gt; status: running
&gt; heap\\_size: 376
&gt; stack\\_size: 27
&gt; reductions: 119
&gt; neighbours:
&gt;
&gt; As I understand it, there is a "notfound" exception but I have no idea
what is missing...

Please advise.

Regards,

-- 
\\*Jean-Marc Le Roux\\*


Founder and CEO of Aerys (http://aerys.in)

Blog: http://blogs.aerys.in/jeanmarc-leroux
Cell: (+33)6 20 56 45 78
Phone: (+33)9 72 40 17 58
\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\\_lists.basho.com

