---
title: "Re: Periodically solr down issue."
description: ""
project: community
lastmod: 2017-02-04T07:32:26-0800
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg17915"
mailinglist_parent_id: "msg17914"
author_name: "Luke Bakken"
project_section: "mailinglistitem"
sent_date: 2017-02-04T07:32:26-0800
---


Hi Alex -

What is in solr.log ?
--
Luke Bakken
Engineer
lbak...@basho.com


On Sat, Feb 4, 2017 at 3:37 AM, Alex Feng  wrote:
> Hello Riak users,
>
> I recently found our solr system got down after running some time, it got
> recovered after a restart. But then it happened again.
>
> Below is the error output, do you guys have any clue about this ?
>
>
> 2017-02-04 18:12:22.329 [error] <0.830.0>@yz\_kv:index\_internal:237 failed to
> index object
> {{<<"process\_test\_result">>,<<83,104,105,76,111,110,103,90,105,9
> 5,77,66,80,65,67,75,45,231,148,159,228,186,167,232,189,166,233,151,180,50,48,49,55,50,52>>},<<"9H5AlII0OZm8xwnGbI">>}
> with error {"Failed to index docs",o
> ther,{error,{conn\_failed,{error,econnrefused}}}} because
> [{yz\_solr,index,3,[{file,"src/yz\_solr.erl"},{line,205}]},{yz\_kv,index,7,[{file,"src/yz\_kv.erl"},{
> line,293}]},{yz\_kv,index\_internal,5,[{file,"src/yz\_kv.erl"},{line,224}]},{riak\_kv\_vnode,actual\_put,6,[{file,"src/riak\_kv\_vnode.erl"},{line,1619}]},{riak\_k
> v\_vnode,perform\_put,3,[{file,"src/riak\_kv\_vnode.erl"},{line,1607}]},{riak\_kv\_vnode,do\_put,7,[{file,"src/riak\_kv\_vnode.erl"},{line,1398}]},{riak\_kv\_vnode,h
> andle\_command,3,[{file,"src/riak\_kv\_vnode.erl"},{line,558}]},{riak\_core\_vnode,vnode\_command,3,[{file,"src/riak\_core\_vnode.erl"},{line,346}]}]
>
>
>
> restart node, got this>
>
>
> 2017-02-04 18:13:47.026 [error] <0.4340.0>@yz\_pb\_search:maybe\_process:111
> {solr\_error,{500,"http://localhost:8093/internal\_solr/process\_test\_result/select
> ",<<"{\"error\":{\"msg\":\"org.apache.solr.client.solrj.SolrServerException:
> Server refused connection at:
> http://nosql-3.dsdb:8093/internal\_solr/process\_
> test\_result\",\"trace\":\"org.apache.solr.common.SolrException:
> org.apache.solr.client.solrj.SolrServerException: Server refused connection
> at: http://nos
> ql-3.dsdb:8093/internal\_solr/process\_test\_result\\n\\tat
> org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:308)\\n\\tat
>
> org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)\\n\\tat
> org.apache.solr.core.SolrCore.execute(SolrCore.java:1916)\\
> n\\tat
> org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:780)\\n\\tat
> org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDis
> patchFilter.java:427)\\n\\tat
> org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:217)\\n\\tat
> org.eclipse.jetty.servlet.ServletHa
> ndler$CachedChain.doFilter(ServletHandler.java:1419)\\n\\tat
> org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)\\n\\tat
> org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)\\n\\tat
> org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)\\n\\tat
> org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)\\n\\tat
> org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)\\n\\tat
> org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)\\n\\tat
> org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)\\n\\tat
> org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)\\n\\tat
> org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)\\n\\tat
> org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)\\n\\tat
> org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)\\n\\tat
> org.eclipse.jetty.server.handler.HandlerWrap...">>}}
> [{yz\_solr,search,3,[{file,"src/yz\_solr.erl"},{line,292}]},{yz\_pb\_search,maybe\_process,3,[{file,"src/yz\_pb\_search.erl"},{line,76}]},{riak\_api\_pb\_server,process\_message,4,[{file,"src/riak\_api\_pb\_server.erl"},{line,388}]},{riak\_api\_pb\_server,connected,2,[{file,"src/riak\_api\_pb\_server.erl"},{line,226}]},{riak\_api\_pb\_server,decode\_buffer,2,[{file,"src/riak\_api\_pb\_server.erl"},{line,364}]},{gen\_fsm,handle\_msg,7,[{file,"gen\_fsm.erl"},{line,505}]},{proc\_lib,init\_p\_do\_apply,3,[{file,"proc\_lib.erl"},{line,239}]}]
> 2017-02-04 18:17:02.756 [error]
> <0.6871.0>@riak\_core\_handoff\_receiver:handle\_info:97 Handoff receiver for
> partition 0 exited abnormally after processing 0 objects from
> {"192.168.9.247",39483}:
> {error,{vnode\_timeout,60000,844,<<131,104,2,100,0,10,101,110,99,111,100,101,95,114,97,119,104,3,104,2,109,0,0,0,19,112,114,111,99,101,115,115,95,116,101,115,116,95,114,101,115,117,108,116,109,0,0,0,35,83,104,105,76,111,110,103,90,105,95,77,66,80,65,67,75,45,231,148,159,228,186,167,232,189,166,233,151,180,50,48,49,55,50,52,109,0,0,0,18,57,72,53,65,109,84,122,54,79,109,99,108,87,107,87,68,80,85,109,0,0,2,220,53,1,0,0,0,38,131,108,0,0,0,1,104,2,109,0>>}}
>
>
> Br,
>
> Alex
>
>
> \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
> riak-users mailing list
> riak-users@lists.basho.com
> http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com
>

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com

