---
title: "Re: Can't delete objects from Riak KV"
description: ""
project: community
lastmod: 2016-04-14T07:08:46-0700
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg17220"
mailinglist_parent_id: "msg17219"
author_name: "Alex De la rosa"
project_section: "mailinglistitem"
sent_date: 2016-04-14T07:08:46-0700
---


I seem to be having this error messages on the log, any ideas?

2016-04-14 16:03:00.460 [error] <0.5460.8143> CRASH REPORT Process
<0.5460.8143> with 0 neighbours crashed with reason: call to undefined
function webmachine\_error\_handler:render\_error(404,
{webmachine\_request,{wm\_reqstate,#Port<0.147587697>,[],undefined,undefined,"xx.xx.xx.xx",{wm\_reqdata,...},...}},
{none,none,[]})
Thanks,
Alex

On Thu, Apr 14, 2016 at 6:04 PM, Luke Bakken  wrote:

> Hi Alex,
>
> Thanks for running that. This proves that it is not a Python client
> issue. You can see the transcript of storing, fetching and deleting an
> object successfully here:
> https://gist.github.com/lukebakken/f1f3cbc96c2762eabb2f124b42797fda
>
> At this point, I suggest checking the error.log files on each Riak
> node for information. Or, if you run "riak-debug" on your cluster and
> provide the archives somewhere (private access), I could take a look.
>
> --
> Luke Bakken
> Engineer
> lbak...@basho.com
>
>
> On Thu, Apr 14, 2016 at 6:57 AM, Alex De la rosa
>  wrote:
> > Hi Luke, I tried and get this and didn't work:
> >
> > ~ # curl -4vvv -XDELETE
> http://xx.xx.xx.xx:8098/buckets/test/keys/something
> > \* Hostname was NOT found in DNS cache
> > \* Trying xx.xx.xx.xx...
> > \* Connected to xx.xx.xx.xx (xx.xx.xx.xx) port 8098 (#0)
> >> DELETE /buckets/test/keys/something HTTP/1.1
> >> User-Agent: curl/7.35.0
> >> Host: xx.xx.xx.xx:8098
> >> Accept: \*/\*
> >>
> > \* Empty reply from server
> > \* Connection #0 to host xx.xx.xx.xx left intact
> > curl: (52) Empty reply from server
> >
> > Thanks,
> > Alex
> >
> > On Thu, Apr 14, 2016 at 5:50 PM, Alex De la rosa <
> alex.rosa....@gmail.com>
> > wrote:
> >>
> >> I can try that, but I would like to do it via the python client
> itself...
> >>
> >> Thanks,
> >> Rohman
> >>
> >> On Thu, Apr 14, 2016 at 5:47 PM, Luke Bakken  wrote:
> >>>
> >>> Hi Alex,
> >>>
> >>> Can you use the HTTP API to delete an object? Something like:
> >>>
> >>> curl -4vvv -XDELETE riak-host:8098/buckets/test/keys/something
> >>>
> >>> --
> >>> Luke Bakken
> >>> Engineer
> >>> lbak...@basho.com
> >>>
> >>>
> >>> On Thu, Apr 14, 2016 at 2:05 AM, Alex De la rosa
> >>>  wrote:
> >>> > I upgraded the Python library to the latest and is still failing...
> I'm
> >>> > unable to delete any objects at all.
> >>> >
> >>> > ~ # pip show riak
> >>> > ---
> >>> > Name: riak
> >>> > Version: 2.4.2
> >>> > Location: /usr/local/lib/python2.7/dist-packages
> >>> > Requires: six, pyOpenSSL, protobuf
> >>> >
> >>> > Everything else seems fine, just timeouts when deleting :(
> >>> >
> >>> > Thanks,
> >>> > Alex
> >>> >
> >>> > On Thu, Apr 14, 2016 at 8:53 AM, Alex De la rosa
> >>> > 
> >>> > wrote:
> >>> >>
> >>> >> Hi there,
> >>> >>
> >>> >> I'm trying to delete objects from riak with the python library and
> is
> >>> >> timing out, any ideas? (this example is from a simple object, but
> also
> >>> >> have
> >>> >> issues with bucket types with map objects, etc...)... Just I seem to
> >>> >> unable
> >>> >> to delete anything, just times out.
> >>> >>
> >>> >> >>> import riak
> >>> >> >>> RIAK = riak.RiakClient(protocol = 'pbc', nodes = [{'host':
> >>> >> >>> '--------',
> >>> >> >>> 'http\_port': 8098, 'pb\_port': 8087}])
> >>> >> >>> x = RIAK.bucket('test').get('something')
> >>> >> >>> print x.data
> >>> >> {"something":"here"}
> >>> >> >>> x.delete()
> >>> >> Traceback (most recent call last):
> >>> >> File "", line 1, in 
> >>> >> File "/usr/local/lib/python2.7/dist-packages/riak/riak\_object.py",
> >>> >> line
> >>> >> 329, in delete
> >>> >> timeout=timeout)
> >>> >> File
> >>> >> "/usr/local/lib/python2.7/dist-packages/riak/client/transport.py",
> >>> >> line 196, in wrapper
> >>> >> return self.\_with\_retries(pool, thunk)
> >>> >> File
> >>> >> "/usr/local/lib/python2.7/dist-packages/riak/client/transport.py",
> >>> >> line 138, in \_with\_retries
> >>> >> return fn(transport)
> >>> >> File
> >>> >> "/usr/local/lib/python2.7/dist-packages/riak/client/transport.py",
> >>> >> line 194, in thunk
> >>> >> return fn(self, transport, \*args, \*\*kwargs)
> >>> >> File
> >>> >> "/usr/local/lib/python2.7/dist-packages/riak/client/operations.py",
> >>> >> line 744, in delete
> >>> >> pw=pw, timeout=timeout)
> >>> >> File
> >>> >>
> >>> >>
> "/usr/local/lib/python2.7/dist-packages/riak/transports/pbc/transport.py",
> >>> >> line 283, in delete
> >>> >> riak.pb.messages.MSG\_CODE\_DEL\_RESP)
> >>> >> File
> >>> >>
> >>> >>
> "/usr/local/lib/python2.7/dist-packages/riak/transports/pbc/connection.py",
> >>> >> line 34, in \_request
> >>> >> return self.\_recv\_msg(expect)
> >>> >> File
> >>> >>
> >>> >>
> "/usr/local/lib/python2.7/dist-packages/riak/transports/pbc/connection.py",
> >>> >> line 165, in \_recv\_msg
> >>> >> raise RiakError(bytes\_to\_str(err.errmsg))
> >>> >> riak.riak\_error.RiakError: 'timeout'
> >>> >>
> >>> >> My Riak version is 2.1.4
> >>> >>
> >>> >> My Python library is (installed via pip):
> >>> >> Name: riak
> >>> >> Version: 2.2.0
> >>> >> Location: /usr/local/lib/python2.7/dist-packages
> >>> >> Requires: six, pyOpenSSL, riak-pb
> >>> >>
> >>> >> Thanks,
> >>> >> Alex
> >>> >
> >>> >
> >>> >
> >>> > \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
> >>> > riak-users mailing list
> >>> > riak-users@lists.basho.com
> >>> > http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com
> >>> >
> >>
> >>
> >
>
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com

