---
title: "Re: Riak server crashing"
description: ""
project: community
lastmod: 2016-05-02T14:52:15-0700
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg17279"
mailinglist_parent_id: "msg17278"
author_name: "Ricardo Mayerhofer"
project_section: "mailinglistitem"
sent_date: 2016-05-02T14:52:15-0700
---


Thanks!

On Mon, May 2, 2016 at 6:48 PM, Ricardo Mayerhofer 
wrote:

> Makes sense, I'll tune it.
>
> On Mon, May 2, 2016 at 11:29 AM, Fred Dushin  wrote:
>
>> Acceptor not being able to create a server side socket smells like you've
>> run out of file descriptors.
>>
>> On May 2, 2016, at 10:25 AM, Ricardo Mayerhofer 
>> wrote:
>>
>> Hi all,
>> I've a riak server that was running fine for 1 month, now it keep
>> crashing. Restart has no effect. Any idea?
>>
>> Riak version 2.13
>>
>> error.log
>>
>> 2016-05-02 14:07:54.871 [error] <0.170.0> Supervisor riak\_core\_vnode\_sup
>> had child undefined started with riak\_core\_vnode:start\_link() at undefined
>> exit with reason {timeout,{gen\_server,call,[<0.2386.190>,stop]}} in context
>> shutdown\_error
>>
>> 2016-05-02 14:07:54.871 [error] <0.170.0> Supervisor riak\_core\_vnode\_sup
>> had child undefined started with riak\_core\_vnode:start\_link() at undefined
>> exit with reason {timeout,{gen\_server,call,[<0.19017.322>,stop]}} in
>> context shutdown\_error
>>
>> 2016-05-02 14:07:54.871 [error] <0.170.0> Supervisor riak\_core\_vnode\_sup
>> had child undefined started with riak\_core\_vnode:start\_link() at undefined
>> exit with reason {timeout,{gen\_server,call,[<0.18706.190>,stop]}} in
>> context shutdown\_error
>>
>> 2016-05-02 14:07:54.871 [error] <0.170.0> Supervisor riak\_core\_vnode\_sup
>> had child undefined started with riak\_core\_vnode:start\_link() at undefined
>> exit with reason {timeout,{gen\_server,call,[<0.19822.324>,stop]}} in
>> context shutdown\_error
>>
>> 2016-05-02 14:07:54.871 [error] <0.170.0> Supervisor riak\_core\_vnode\_sup
>> had child undefined started with riak\_core\_vnode:start\_link() at undefined
>> exit with reason {timeout,{gen\_server,call,[<0.2857.0>,stop]}} in context
>> shutdown\_error
>>
>> 2016-05-02 14:07:54.871 [error] <0.170.0> Supervisor riak\_core\_vnode\_sup
>> had child undefined started with riak\_core\_vnode:start\_link() at undefined
>> exit with reason {timeout,{gen\_server,call,[<0.2786.0>,stop]}} in context
>> shutdown\_error
>>
>> 2016-05-02 14:07:54.871 [error] <0.170.0> Supervisor riak\_core\_vnode\_sup
>> had child undefined started with riak\_core\_vnode:start\_link() at undefined
>> exit with reason {timeout,{gen\_server,call,[<0.2626.0>,stop]}} in context
>> shutdown\_error
>>
>> 2016-05-02 14:07:54.871 [error] <0.170.0> Supervisor riak\_core\_vnode\_sup
>> had child undefined started with riak\_core\_vnode:start\_link() at undefined
>> exit with reason {timeout,{gen\_server,call,[<0.5208.180>,stop]}} in context
>> shutdown\_error
>>
>> 2016-05-02 14:07:54.872 [error] <0.170.0> Supervisor riak\_core\_vnode\_sup
>> had child undefined started with riak\_core\_vnode:start\_link() at undefined
>> exit with reason {timeout,{gen\_server,call,[<0.2562.0>,stop]}} in context
>> shutdown\_error
>>
>> 2016-05-02 14:07:54.872 [error] <0.170.0> Supervisor riak\_core\_vnode\_sup
>> had child undefined started with riak\_core\_vnode:start\_link() at undefined
>> exit with reason bad argument in call to ets:lookup(riak\_core\_node\_watcher,
>> {by\_node,'riak@127.0.0.1'}) in
>> riak\_core\_node\_watcher:internal\_get\_services/1 line 548 in context
>> shutdown\_error
>>
>> 2016-05-02 14:17:27.739 [error] <0.4518.0> application: mochiweb, "Accept
>> failed error", "{error,emfile}"
>>
>> 2016-05-02 14:17:27.739 [error] <0.4518.0> CRASH REPORT Process
>> <0.4518.0> with 0 neighbours exited with reason: {error,accept\_failed} in
>> mochiweb\_acceptor:init/3 line 33
>>
>> 2016-05-02 14:17:27.739 [error] <0.308.0>
>> {mochiweb\_socket\_server,320,{acceptor\_error,{error,accept\_failed}}}
>>
>> 2016-05-02 14:17:27.739 [error] <0.5153.0> application: mochiweb, "Accept
>> failed error", "{error,emfile}"
>>
>> 2016-05-02 14:17:27.739 [error] <0.5153.0> CRASH REPORT Process
>> <0.5153.0> with 0 neighbours exited with reason: {error,accept\_failed} in
>> mochiweb\_acceptor:init/3 line 33
>>
>> 2016-05-02 14:17:27.739 [error] <0.5156.0> application: mochiweb, "Accept
>> failed error", "{error,emfile}"
>>
>> 2016-05-02 14:17:27.739 [error] <0.5156.0> CRASH REPORT Process
>> <0.5156.0> with 0 neighbours exited with reason: {error,accept\_failed} in
>> mochiweb\_acceptor:init/3 line 33
>>
>> 2016-05-02 14:17:27.739 [error] <0.5216.0> application: mochiweb, "Accept
>> failed error", "{error,emfile}"
>>
>> 2016-05-02 14:17:27.739 [error] <0.5216.0> CRASH REPORT Process
>> <0.5216.0> with 0 neighbours exited with reason: {error,accept\_failed} in
>> mochiweb\_acceptor:init/3 line 33
>>
>> 2016-05-02 14:17:27.740 [error] <0.5090.0> application: mochiweb, "Accept
>> failed error", "{error,emfile}"
>>
>> 2016-05-02 14:17:27.740 [error] <0.5090.0> CRASH REPORT Process
>> <0.5090.0> with 0 neighbours exited with reason: {error,accept\_failed} in
>> mochiweb\_acceptor:init/3 line 33
>>
>> 2016-05-02 14:17:27.740 [error] <0.5165.0> application: mochiweb, "Accept
>> failed error", "{error,emfile}"
>>
>> 2016-05-02 14:17:27.740 [error] <0.5165.0> CRASH REPORT Process
>> <0.5165.0> with 0 neighbours exited with reason: {error,accept\_failed} in
>> mochiweb\_acceptor:init/3 line 33
>>
>> 2016-05-02 14:17:27.740 [error] <0.5167.0> application: mochiweb, "Accept
>> failed error", "{error,emfile}"
>>
>> 2016-05-02 14:17:27.740 [error] <0.5167.0> CRASH REPORT Process
>> <0.5167.0> with 0 neighbours exited with reason: {error,accept\_failed} in
>> mochiweb\_acceptor:init/3 line 33
>>
>> 2016-05-02 14:17:27.740 [error] <0.5103.0> application: mochiweb, "Accept
>> failed error", "{error,emfile}"
>>
>> 2016-05-02 14:17:27.740 [error] <0.5103.0> CRASH REPORT Process
>> <0.5103.0> with 0 neighbours exited with reason: {error,accept\_failed} in
>> mochiweb\_acceptor:init/3 line 33
>>
>> 2016-05-02 14:17:27.740 [error] <0.5141.0> application: mochiweb, "Accept
>> failed error", "{error,emfile}"
>>
>> 2016-05-02 14:17:27.740 [error] <0.5141.0> CRASH REPORT Process
>> <0.5141.0> with 0 neighbours exited with reason: {error,accept\_failed} in
>> mochiweb\_acceptor:init/3 line 33
>>
>> 2016-05-02 14:17:27.740 [error] <0.5332.0> application: mochiweb, "Accept
>> failed error", "{error,emfile}"
>>
>> 2016-05-02 14:17:27.740 [error] <0.5332.0> CRASH REPORT Process
>> <0.5332.0> with 0 neighbours exited with reason: {error,accept\_failed} in
>> mochiweb\_acceptor:init/3 line 33
>>
>> 2016-05-02 14:17:27.740 [error] <0.5334.0> application: mochiweb, "Accept
>> failed error", "{error,emfile}"
>>
>> 2016-05-02 14:17:27.740 [error] <0.5334.0> CRASH REPORT Process
>> <0.5334.0> with 0 neighbours exited with reason: {error,accept\_failed} in
>> mochiweb\_acceptor:init/3 line 33
>>
>> 2016-05-02 14:17:27.740 [error] <0.4460.0> application: mochiweb, "Accept
>> failed error", "{error,emfile}"
>>
>> 2016-05-02 14:17:27.740 [error] <0.4460.0> CRASH REPORT Process
>> <0.4460.0> with 0 neighbours exited with reason: {error,accept\_failed} in
>> mochiweb\_acceptor:init/3 line 33
>>
>>
>>
>> --
>> Ricardo Mayerhofer
>> \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
>> riak-users mailing list
>> riak-users@lists.basho.com
>> http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com
>>
>>
>>
>> \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
>> riak-users mailing list
>> riak-users@lists.basho.com
>> http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com
>>
>>
>
>
> --
> Ricardo Mayerhofer
>



-- 
Ricardo Mayerhofer
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com

