---
title: "Re: Can't delete objects from Riak KV"
description: ""
project: community
lastmod: 2016-04-14T02:07:17-07:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg17214"
mailinglist_parent_id: "msg17213"
author_name: "Alex De la rosa"
project_section: "mailinglistitem"
sent_date: 2016-04-14T02:07:17-07:00
---


I upgraded the Python library to the latest and is still failing... I'm
unable to delete any objects at all.

~ # pip show riak
---
Name: riak
Version: 2.4.2
Location: /usr/local/lib/python2.7/dist-packages
Requires: six, pyOpenSSL, protobuf

Everything else seems fine, just timeouts when deleting :(

Thanks,
Alex

On Thu, Apr 14, 2016 at 8:53 AM, Alex De la rosa 
wrote:

&gt; Hi there,
&gt;
&gt; I'm trying to delete objects from riak with the python library and is
&gt; timing out, any ideas? (this example is from a simple object, but also have
&gt; issues with bucket types with map objects, etc...)... Just I seem to unable
&gt; to delete anything, just times out.
&gt;
&gt;
&gt;
&gt;
&gt;
&gt;
&gt;
&gt;
&gt;
&gt;
&gt;
&gt;
&gt;
&gt;
&gt;
&gt;
&gt;
&gt;
&gt;
&gt;
&gt;
&gt;
&gt;
&gt;
&gt;
&gt; \*&gt;&gt;&gt; import riak&gt;&gt;&gt; RIAK = riak.RiakClient(protocol = 'pbc', nodes =
&gt; [{'host': '--------', 'http\_port': 8098, 'pb\_port': 8087}])&gt;&gt;&gt; x =
&gt; RIAK.bucket('test').get('something')&gt;&gt;&gt; print x.data{"something":"here"}&gt;&gt;&gt;
&gt; x.delete()Traceback (most recent call last): File "", line 1, in
&gt;  File
&gt; "/usr/local/lib/python2.7/dist-packages/riak/riak\_object.py", line 329, in
&gt; delete timeout=timeout) File
&gt; "/usr/local/lib/python2.7/dist-packages/riak/client/transport.py", line
&gt; 196, in wrapper return self.\_with\_retries(pool, thunk) File
&gt; "/usr/local/lib/python2.7/dist-packages/riak/client/transport.py", line
&gt; 138, in \_with\_retries return fn(transport) File
&gt; "/usr/local/lib/python2.7/dist-packages/riak/client/transport.py", line
&gt; 194, in thunk return fn(self, transport, \*args, \*\*kwargs) File
&gt; "/usr/local/lib/python2.7/dist-packages/riak/client/operations.py", line
&gt; 744, in delete pw=pw, timeout=timeout) File
&gt; "/usr/local/lib/python2.7/dist-packages/riak/transports/pbc/transport.py",
&gt; line 283, in delete riak.pb.messages.MSG\_CODE\_DEL\_RESP) File
&gt; "/usr/local/lib/python2.7/dist-packages/riak/transports/pbc/connection.py",
&gt; line 34, in \_request return self.\_recv\_msg(expect) File
&gt; "/usr/local/lib/python2.7/dist-packages/riak/transports/pbc/connection.py",
&gt; line 165, in \_recv\_msg raise
&gt; RiakError(bytes\_to\_str(err.errmsg))riak.riak\_error.RiakError: 'timeout'\*
&gt;
&gt; My Riak version is 2.1.4
&gt;
&gt; My Python library is (installed via pip):
&gt; Name: riak
&gt; Version: 2.2.0
&gt; Location: /usr/local/lib/python2.7/dist-packages
&gt; Requires: six, pyOpenSSL, riak-pb
&gt;
&gt; Thanks,
&gt; Alex
&gt;
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com

