---
title: "Riak server crashing"
description: ""
project: community
lastmod: 2016-05-02T07:27:09-07:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg17269"
author_name: "Ricardo Mayerhofer"
project_section: "mailinglistitem"
sent_date: 2016-05-02T07:27:09-07:00
---


Hi all,
I've a riak server that was running fine for 1 month, now it keep crashing.
Restart has no effect. Any idea?

Riak version 2.13

error.log

2016-05-02 14:07:54.871 [error] &lt;0.170.0&gt; Supervisor riak\_core\_vnode\_sup
had child undefined started with riak\_core\_vnode:start\_link() at undefined
exit with reason {timeout,{gen\_server,call,[&lt;0.2386.190&gt;,stop]}} in context
shutdown\_error

2016-05-02 14:07:54.871 [error] &lt;0.170.0&gt; Supervisor riak\_core\_vnode\_sup
had child undefined started with riak\_core\_vnode:start\_link() at undefined
exit with reason {timeout,{gen\_server,call,[&lt;0.19017.322&gt;,stop]}} in
context shutdown\_error

2016-05-02 14:07:54.871 [error] &lt;0.170.0&gt; Supervisor riak\_core\_vnode\_sup
had child undefined started with riak\_core\_vnode:start\_link() at undefined
exit with reason {timeout,{gen\_server,call,[&lt;0.18706.190&gt;,stop]}} in
context shutdown\_error

2016-05-02 14:07:54.871 [error] &lt;0.170.0&gt; Supervisor riak\_core\_vnode\_sup
had child undefined started with riak\_core\_vnode:start\_link() at undefined
exit with reason {timeout,{gen\_server,call,[&lt;0.19822.324&gt;,stop]}} in
context shutdown\_error

2016-05-02 14:07:54.871 [error] &lt;0.170.0&gt; Supervisor riak\_core\_vnode\_sup
had child undefined started with riak\_core\_vnode:start\_link() at undefined
exit with reason {timeout,{gen\_server,call,[&lt;0.2857.0&gt;,stop]}} in context
shutdown\_error

2016-05-02 14:07:54.871 [error] &lt;0.170.0&gt; Supervisor riak\_core\_vnode\_sup
had child undefined started with riak\_core\_vnode:start\_link() at undefined
exit with reason {timeout,{gen\_server,call,[&lt;0.2786.0&gt;,stop]}} in context
shutdown\_error

2016-05-02 14:07:54.871 [error] &lt;0.170.0&gt; Supervisor riak\_core\_vnode\_sup
had child undefined started with riak\_core\_vnode:start\_link() at undefined
exit with reason {timeout,{gen\_server,call,[&lt;0.2626.0&gt;,stop]}} in context
shutdown\_error

2016-05-02 14:07:54.871 [error] &lt;0.170.0&gt; Supervisor riak\_core\_vnode\_sup
had child undefined started with riak\_core\_vnode:start\_link() at undefined
exit with reason {timeout,{gen\_server,call,[&lt;0.5208.180&gt;,stop]}} in context
shutdown\_error

2016-05-02 14:07:54.872 [error] &lt;0.170.0&gt; Supervisor riak\_core\_vnode\_sup
had child undefined started with riak\_core\_vnode:start\_link() at undefined
exit with reason {timeout,{gen\_server,call,[&lt;0.2562.0&gt;,stop]}} in context
shutdown\_error

2016-05-02 14:07:54.872 [error] &lt;0.170.0&gt; Supervisor riak\_core\_vnode\_sup
had child undefined started with riak\_core\_vnode:start\_link() at undefined
exit with reason bad argument in call to ets:lookup(riak\_core\_node\_watcher,
{by\_node,'riak@127.0.0.1'}) in
riak\_core\_node\_watcher:internal\_get\_services/1 line 548 in context
shutdown\_error

2016-05-02 14:17:27.739 [error] &lt;0.4518.0&gt; application: mochiweb, "Accept
failed error", "{error,emfile}"

2016-05-02 14:17:27.739 [error] &lt;0.4518.0&gt; CRASH REPORT Process &lt;0.4518.0&gt;
with 0 neighbours exited with reason: {error,accept\_failed} in
mochiweb\_acceptor:init/3 line 33

2016-05-02 14:17:27.739 [error] &lt;0.308.0&gt;
{mochiweb\_socket\_server,320,{acceptor\_error,{error,accept\_failed}}}

2016-05-02 14:17:27.739 [error] &lt;0.5153.0&gt; application: mochiweb, "Accept
failed error", "{error,emfile}"

2016-05-02 14:17:27.739 [error] &lt;0.5153.0&gt; CRASH REPORT Process &lt;0.5153.0&gt;
with 0 neighbours exited with reason: {error,accept\_failed} in
mochiweb\_acceptor:init/3 line 33

2016-05-02 14:17:27.739 [error] &lt;0.5156.0&gt; application: mochiweb, "Accept
failed error", "{error,emfile}"

2016-05-02 14:17:27.739 [error] &lt;0.5156.0&gt; CRASH REPORT Process &lt;0.5156.0&gt;
with 0 neighbours exited with reason: {error,accept\_failed} in
mochiweb\_acceptor:init/3 line 33

2016-05-02 14:17:27.739 [error] &lt;0.5216.0&gt; application: mochiweb, "Accept
failed error", "{error,emfile}"

2016-05-02 14:17:27.739 [error] &lt;0.5216.0&gt; CRASH REPORT Process &lt;0.5216.0&gt;
with 0 neighbours exited with reason: {error,accept\_failed} in
mochiweb\_acceptor:init/3 line 33

2016-05-02 14:17:27.740 [error] &lt;0.5090.0&gt; application: mochiweb, "Accept
failed error", "{error,emfile}"

2016-05-02 14:17:27.740 [error] &lt;0.5090.0&gt; CRASH REPORT Process &lt;0.5090.0&gt;
with 0 neighbours exited with reason: {error,accept\_failed} in
mochiweb\_acceptor:init/3 line 33

2016-05-02 14:17:27.740 [error] &lt;0.5165.0&gt; application: mochiweb, "Accept
failed error", "{error,emfile}"

2016-05-02 14:17:27.740 [error] &lt;0.5165.0&gt; CRASH REPORT Process &lt;0.5165.0&gt;
with 0 neighbours exited with reason: {error,accept\_failed} in
mochiweb\_acceptor:init/3 line 33

2016-05-02 14:17:27.740 [error] &lt;0.5167.0&gt; application: mochiweb, "Accept
failed error", "{error,emfile}"

2016-05-02 14:17:27.740 [error] &lt;0.5167.0&gt; CRASH REPORT Process &lt;0.5167.0&gt;
with 0 neighbours exited with reason: {error,accept\_failed} in
mochiweb\_acceptor:init/3 line 33

2016-05-02 14:17:27.740 [error] &lt;0.5103.0&gt; application: mochiweb, "Accept
failed error", "{error,emfile}"

2016-05-02 14:17:27.740 [error] &lt;0.5103.0&gt; CRASH REPORT Process &lt;0.5103.0&gt;
with 0 neighbours exited with reason: {error,accept\_failed} in
mochiweb\_acceptor:init/3 line 33

2016-05-02 14:17:27.740 [error] &lt;0.5141.0&gt; application: mochiweb, "Accept
failed error", "{error,emfile}"

2016-05-02 14:17:27.740 [error] &lt;0.5141.0&gt; CRASH REPORT Process &lt;0.5141.0&gt;
with 0 neighbours exited with reason: {error,accept\_failed} in
mochiweb\_acceptor:init/3 line 33

2016-05-02 14:17:27.740 [error] &lt;0.5332.0&gt; application: mochiweb, "Accept
failed error", "{error,emfile}"

2016-05-02 14:17:27.740 [error] &lt;0.5332.0&gt; CRASH REPORT Process &lt;0.5332.0&gt;
with 0 neighbours exited with reason: {error,accept\_failed} in
mochiweb\_acceptor:init/3 line 33

2016-05-02 14:17:27.740 [error] &lt;0.5334.0&gt; application: mochiweb, "Accept
failed error", "{error,emfile}"

2016-05-02 14:17:27.740 [error] &lt;0.5334.0&gt; CRASH REPORT Process &lt;0.5334.0&gt;
with 0 neighbours exited with reason: {error,accept\_failed} in
mochiweb\_acceptor:init/3 line 33

2016-05-02 14:17:27.740 [error] &lt;0.4460.0&gt; application: mochiweb, "Accept
failed error", "{error,emfile}"

2016-05-02 14:17:27.740 [error] &lt;0.4460.0&gt; CRASH REPORT Process &lt;0.4460.0&gt;
with 0 neighbours exited with reason: {error,accept\_failed} in
mochiweb\_acceptor:init/3 line 33



-- 
Ricardo Mayerhofer
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com

