---
title: "Re: Search Crashes"
description: ""
project: community
lastmod: 2013-11-22T20:09:25-08:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg13067"
mailinglist_parent_id: "msg13052"
author_name: "Gabriel Littman"
project_section: "mailinglistitem"
sent_date: 2013-11-22T20:09:25-08:00
---


Hi Ryan,

You are a rock star. I owe you $5.

The bucket had allow\_mult set to true:
$ curl 'http://10.1.2.95:8098/buckets/\_rsid\_ctv\_tvdata/props'
{"props":{"name":"\_rsid\_ctv\_tvdata","allow\_mult":true,"basic\_quorum":false,"big\_vclock":50,"chash\_keyfun":{"mod":"riak\_core\_util","fun":"chash\_std\_keyfun"},"dw":0,"last\_write\_wins":false,"linkfun":{"mod":"riak\_kv\_wm\_link\_walker","fun":"mapreduce\_linkfun"},"n\_val":3,"notfound\_ok":false,"old\_vclock":86400,"postcommit":[],"pr":0,"precommit":[],"pw":0,"r":1,"rw":1,"small\_vclock":50,"w":1,"young\_vclock":20}}

I fixed it in the python console since that is where I'm more comfortable.
 And just to be sure I attempted the same riak PUT both before and after.

>>> import riak
>>> r = riak.RiakClient()
>>> b = r.bucket('ctv\_tvdata')
>>> o = b.get('/data/v2/search\_show/TMS.Show.9838380')
>>> o.store()
Traceback (most recent call last):
 File "", line 1, in 
 File "/usr/local/lib/python2.7/dist-packages/riak/riak\_object.py", line
281, in store
 timeout=timeout)
 File "/usr/local/lib/python2.7/dist-packages/riak/client/transport.py",
line 127, in wrapper
 return self.\_with\_retries(pool, thunk)
 File "/usr/local/lib/python2.7/dist-packages/riak/client/transport.py",
line 69, in \_with\_retries
 return fn(transport)
 File "/usr/local/lib/python2.7/dist-packages/riak/client/transport.py",
line 125, in thunk
 return fn(self, transport, \*args, \*\*kwargs)
 File "/usr/local/lib/python2.7/dist-packages/riak/client/operations.py",
line 289, in put
 timeout=timeout)
 File
"/usr/local/lib/python2.7/dist-packages/riak/transports/http/transport.py",
line 144, in put
 return self.\_parse\_body(robj, response, [200, 201, 204, 300])
 File
"/usr/local/lib/python2.7/dist-packages/riak/transports/http/codec.py",
line 64, in \_parse\_body
 self.check\_http\_code(status, expected\_statuses)
 File
"/usr/local/lib/python2.7/dist-packages/riak/transports/http/transport.py",
line 446, in check\_http\_code
 (expected\_statuses, status))
Exception: Expected status [200, 201, 204, 300], received 500
>>> b2 = r.bucket('\_rsid\_ctv\_tvdata')
>>> b2.get\_properties()
{'old\_vclock': 86400, 'pr': 0, 'allow\_mult': True, 'big\_vclock': 50,
'name': '\_rsid\_ctv\_tvdata', 'chash\_keyfun': {'fun': 'chash\_std\_keyfun',
'mod': 'riak\_core\_util'}, 'n\_val': 3, 'notfound\_ok': False, 'linkfun':
{'fun': 'mapreduce\_linkfun', 'mod': 'riak\_kv\_wm\_link\_walker'}, 'pw': 0,
'last\_write\_wins': False, 'r': 1, 'small\_vclock': 50, 'rw': 1,
'basic\_quorum': False, 'postcommit': [], 'dw': 0, 'w': 1, 'young\_vclock':
20, 'precommit': []}
>>> b2.set\_property('allow\_mult', False)
>>> o = b.get('/data/v2/search\_show/TMS.Show.9838380')
>>> o.store()


As you can see it worked like a charm. Thank you so much for your help.
 I never would have figured this out on my own.

Once again, you rock,

Gabe
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com

