---
title: "Re: Upgrade to 1.1.2 problems"
description: ""
project: community
lastmod: 2012-04-26T07:18:51-07:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg07330"
mailinglist_parent_id: "msg07328"
author_name: "Phil Sorber"
project_section: "mailinglistitem"
sent_date: 2012-04-26T07:18:51-07:00
---


Joe,

I think you hit the nail on the head. We install from your released
deb's, but we deploy via chef and have the config generated from a
template. I am going to set up another test this morning and I will
let you know how it goes.

Thanks.

On Wed, Apr 25, 2012 at 7:38 PM, Joseph Blomstedt  wrote:
> Phil,
>
> Given the following lines,
>
>>         {reason,
>>          {{badmatch,{'EXIT',noproc}},
>>           [{riak\_core\_vnode\_proxy,call,2},
>
> I'm inclined to think this is an issue with the new vnode routing
> layer introduced in Riak 1.1. On your Riak 1.1.2 node, make sure your
> app.config does not contain {legacy\_vnode\_routing, false} in the
> riak\_core section. If it does, either delete the line or change it to
> false. If this was the issue, you should set it back to false after
> upgrading the rest of your cluster.
>
> Also, if this turns out to be the issue, could you please let me know
> how you performed the upgrade? Our official packages are supposed to
> be designed so that they retain your old app.config file when
> installed over an existing Riak installation (and thus, this line
> would have been missing from the 1.0.3 config). It would be useful to
> know if you used an official package and the app.config was
> overwritten, or if you manually setup your app.config and simply
> missed this option.
>
> On the plus side, the next release of Riak should include built-in
> capability negotiation that should remove the need for users to have
> to manually deal with legacy, mapred, listkeys, etc settings during an
> upgrade.
>
> -Joe
>
> On Wed, Apr 25, 2012 at 2:05 PM, Phil Sorber  wrote:
>> We have a 4 node riak 1.0.0 cluster running in production that we want
>> to upgrade to 1.1.2. We set up a test environment that closely mimic's
>> the production one. As close as we possibly can with ec2 hosts. First
>> attempt to jump from 1.0.0 -> 1.1.2 failed. We took into account the
>> mapred\_system issue and the listkeys\_backpressure issue. We decided to
>> try 1.0.0 -> 1.0.3 since that would involve the mapred\_system issue
>> only. That upgrade worked. We then tried to upgrade 1.0.3 -> 1.1.2 and
>> had similar problems. Details below.
>>
>> --
>> # riak-admin transfers
>> Attempting to restart script through sudo -u riak
>> 'riak@50.16.31.226' waiting to handoff 14 partitions
>> --
>>
>> Sometimes this would show as many as 48 transfers. Always from the
>> node that we upgraded. It would eventually show no transfers left. The
>> upgrade from 1.0.0 -> 1.0.3 didn't do this.
>>
>> We tested a link walking query that is similar to what we run in
>> production. On 2 of the 3 nodes still running 1.0.3 it worked fine. On
>> the 3rd node, this happened:
>>
>> Curl run on 1.0.3 node:
>>
>> --
>> curl -v http://localhost:8098/riak/email\_address/riakupgr...@gmail.com/\_,\_,1
>> \* About to connect() to localhost port 8098 (#0)
>> \*   Trying 127.0.0.1... connected
>> \* Connected to localhost (127.0.0.1) port 8098 (#0)
>>> GET /riak/email\_address/riakupgr...@gmail.com/\_,\_,1 HTTP/1.1
>>> User-Agent: curl/7.19.7 (x86\_64-pc-linux-gnu) libcurl/7.19.7 OpenSSL/0.9.8k 
>>> zlib/1.2.3.3 libidn/1.15
>>> Host: localhost:8098
>>> Accept: \*/\*
>>>
>> < HTTP/1.1 500 Internal Server Error
>> < Server: MochiWeb/1.1 WebMachine/1.9.0 (someone had painted it blue)
>> < Expires: Wed, 25 Apr 2012 20:55:30 GMT
>> < Date: Wed, 25 Apr 2012 20:45:30 GMT
>> < Content-Type: text/html
>> < Content-Length: 2068
>> <
>> 500 Internal Server
>> ErrorInternal Server Error
=====================

The server
>> encountered an error while processing this request:  

```
{error,
>>  {error,
>>  {badmatch,
>>   {eoi,[],
>>    [{{reduce,0},
>>      {trace,
>>       [error],
>>       {error,
>>        [{module,riak_kv_w_reduce},
>>         {partition,1438665674247607560106752257205091097473808596992},
>>         {details,
>>          [{fitting,
>>            {fitting,<0.848.0>,#Ref<0.0.0.5472>,
>>             #Fun,1}},
>>           {name,{reduce,0}},
>>           {module,riak\_kv\_w\_reduce},
>>           {arg,{rct,#Fun,none}},
>>           {output,
>>            {fitting,<0.847.0>,#Ref<0.0.0.5472>,
>>             #Fun,
>>             #Fun}},
>>           {options,
>>            [{sink,{fitting,<0.119.0>,#Ref<0.0.0.5472>,sink,undefined}},
>>             {log,sink},
>>             {trace,
>>              {set,1,16,16,8,80,48,
>>               {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
>>               {{[],[],[error],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}]},
>>           {q\_limit,64}]},
>>         {reason,
>>          {{badmatch,{'EXIT',noproc}},
>>           [{riak\_core\_vnode\_proxy,call,2},
>>            {riak\_pipe\_vnode,queue\_work\_send,4},
>>            {riak\_pipe\_vnode,queue\_work\_erracc,6},
>>            {riak\_kv\_w\_reduce,'-done/1-lc$^0/1-0-',3},
>>            {riak\_kv\_w\_reduce,done,1},
>>            {riak\_pipe\_vnode\_worker,wait\_for\_input,2},
>>            {gen\_fsm,handle\_msg,7},
>>            {proc\_lib,init\_p\_do\_apply,3}]}},
>>         {state,{working,done}}]}}}]}},
>>  [{riak\_kv\_mrc\_pipe,collect\_outputs,3},
>>   {riak\_kv\_wm\_link\_walker,execute\_segment,3},
>>   {riak\_kv\_wm\_link\_walker,execute\_query,3},
>>   {riak\_kv\_wm\_link\_walker,to\_multipart\_mixed,2},
>>   {webmachine\_resource,resource\_call,3},
>>   {webmachine\_resource,do,3},
>>   {webmachine\_decision\_core,resource\_call,1},
>>   
>> {webmachine\_decision\_core,decision,1}]}}
```


---

mochiweb+webmachine
>> web server> \* Closing connection #0
>> --
>>
>> After that, this appeared in the error.log on that node:
>>
>> error.log on 1.0.3 node:
>>
>> --
>> 2012-04-25 20:45:30.373 [error] <0.119.0> webmachine error:
>> path="/riak/email\_address/riakupgr...@gmail.com/\_,\_,1"
>> {error,{error,{badmatch,{eoi,[],[{{reduce,0},{trace,[error],{error,[{module,riak\_kv\_w\_reduce},{partition,1438665674247607560106752257205091097473808596992},{details,[{fitting,{fitting,<0.848.0>,#Ref<0.0.0.5472>,#Fun,1}},{name,{reduce,0}},{module,riak\_kv\_w\_reduce},{arg,{rct,#Fun,none}},{output,{fitting,<0.847.0>,#Ref<0.0.0.5472>,#Fun,#Fun}},{options,[{sink,{fitting,<0.119.0>,#Ref<0.0.0.5472>,sink,undefined}},{log,sink},{trace,{set,1,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[error],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}]},{q\_limit,64}]},{reason,{{badmatch,{'EXIT',noproc}},[{riak\_core\_vnode\_proxy,call,2},{riak\_pipe\_vnode,queue\_work\_send,4},{riak\_pipe\_vnode,queue\_work\_erracc,6},{riak\_kv\_w\_reduce,'-done/1-lc$^0/1-0-',3},{riak\_kv\_w\_reduce,done,1},{riak\_pipe\_vnode\_worker,wait\_for\_input,2},{gen\_fsm,handle\_msg,7},{proc\_lib,init\_p\_do\_apply,3}]}},{state,{working,done}}]}}}]}},[{riak\_kv\_mrc\_pipe,collect\_outputs,3},{riak\_kv\_wm\_link\_walker,execute\_segment,3},{riak\_kv\_wm\_link\_walker,execute\_query,3},{riak\_kv\_wm\_link\_walker,to\_multipart\_mixed,2},{webmachine\_resource,resource\_call,3},{webmachine\_resource,do,3},{webmachine\_decision\_core,resource\_call,1},{webmachine\_decision\_core,decision,1}]}}
>> --
>>
>> And this was in the error.log on the 1.1.2 node:
>>
>> error.log on 1.1.2 node:
>>
>> --
>> 2012-04-25 20:45:30.234 [error] <0.1710.0> gen\_fsm <0.1710.0> in state
>> wait\_for\_input terminated with reason: no match of right hand value
>> {'EXIT',noproc} in riak\_core\_vnode\_proxy:call/2
>> 2012-04-25 20:45:30.243 [error] <0.1710.0> CRASH REPORT Process
>> <0.1710.0> with 0 neighbours crashed with reason: no match of right
>> hand value {'EXIT',noproc} in riak\_core\_vnode\_proxy:call/2
>> 2012-04-25 20:45:30.245 [error] <0.331.0> Supervisor
>> riak\_pipe\_vnode\_worker\_sup had child undefined started with
>> {riak\_pipe\_vnode\_worker,start\_link,undefined} at <0.1710.0> exit with
>> reason no match of right hand value {'EXIT',noproc} in
>> riak\_core\_vnode\_proxy:call/2 in context child\_terminated
>> --
>>
>> On the 1.1.2 node, running the same curl, it returned a 404 after a
>> long timeout:
>>
>> Curl run on the 1.1.2 node:
>>
>> --
>> curl -v http://localhost:8098/riak/email\_address/riakupgr...@gmail.com/\_,\_,1
>> \* About to connect() to localhost port 8098 (#0)
>> \*   Trying 127.0.0.1... connected
>> \* Connected to localhost (127.0.0.1) port 8098 (#0)
>>> GET /riak/email\_address/riakupgr...@gmail.com/\_,\_,1 HTTP/1.1
>>> User-Agent: curl/7.19.7 (x86\_64-pc-linux-gnu) libcurl/7.19.7 OpenSSL/0.9.8k 
>>> zlib/1.2.3.3 libidn/1.15
>>> Host: localhost:8098
>>> Accept: \*/\*
>>>
>> < HTTP/1.1 404 Object Not Found
>> < Server: MochiWeb/1.1 WebMachine/1.9.0 (someone had painted it blue)
>> < Date: Wed, 25 Apr 2012 20:49:40 GMT
>> < Content-Type: text/html
>> < Content-Length: 193
>> <
>> \* Connection #0 to host localhost left intact
>> \* Closing connection #0
>> 404 Not FoundNot
>> Found
============

The requested document was not found on this
>> server.

---

mochiweb+webmachine web
>> server


>> --
>>
>> There was nothing more in any error logs after this. Also pulling up
>> direct keys fails on this node. Riak is installed from the debian
>> packages. I can send you whatever other info is neccesary. We tried
>> many different combinations, but I think this one is the most correct
>> and produced the most useful error messages. Any help is appreciated.
>>
>> Thanks.
>>
>> \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
>> riak-users mailing list
>> riak-users@lists.basho.com
>> http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com
>
>
>
> --
> Joseph Blomstedt 
> Software Engineer
> Basho Technologies, Inc.
> http://www.basho.com/

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com



