---
title: "Re: Riak 1.3.1 refusing to start up"
description: ""
project: community
lastmod: 2013-04-24T03:27:42-07:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg10960"
mailinglist_parent_id: "msg10959"
author_name: "Chris Read"
project_section: "mailinglistitem"
sent_date: 2013-04-24T03:27:42-07:00
---


Excellent, thanks! Bug in our chef template for vm.args messed up the the
name. All good now.


On Wed, Apr 24, 2013 at 10:51 AM, Eric Redmond  wrote:

> This commonly happens if a node name or IP has changed args.vm -name
> without notifying the ring. Either use the riak-admin cluster replaced
> command, or delete the ring directory and rejoin the cluster.
>
> Note this isn't the only reason for missing capabilities, but a very
> common one.
>
> Sent from my iPhone
>
> On Apr 24, 2013, at 11:11 AM, Chris Read  wrote:
>
> > Greetings all...
> >
> > I've got a riak cluster that's now refusing to start. We're running
> version 1.3.1 on 3 nodes, all of them fail to start with the following
> error in console.log:
> >
> > 2013-04-24 04:05:15.518 [error] <0.152.0> gen\_server
> riak\_core\_capability terminated with reason: no function clause matching
> orddict:fetch(riak@in, []) line 72
> > 2013-04-24 04:05:15.522 [error] <0.152.0> CRASH REPORT Process
> riak\_core\_capability with 0 neighbours exited with reason: no function
> clause matching orddict:fetch(riak@in, []) line 72 in
> gen\_server:terminate/6 line 747
> > 2013-04-24 04:05:15.527 [error] <0.133.0> Supervisor riak\_core\_sup had
> child riak\_core\_capability started with riak\_core\_capability:start\_link()
> at <0.152.0> exit with reason no function clause matching
> orddict:fetch(riak@in, []) line 72 in context child\_terminated
> > 2013-04-24 04:05:15.529 [error] <0.131.0> CRASH REPORT Process <0.131.0>
> with 0 neighbours exited with reason:
> {{function\_clause,[{orddict,fetch,[riak@in,[]],[{file,"orddict.erl"},{line,72}]},{riak\_core\_capability,renegotiate\_capabilities,1,[{file,"src/riak\_core\_capability.erl"},{line,415}]},{riak\_core\_capability,handle\_call,3,[{file,"src/riak\_core\_capability.erl"},{line,208}]},{gen\_server,handle\_msg,5,[{file,"gen\_server.erl"},{line,588}]},{proc\_lib,init\_p\_do\_apply,3,[{file,"proc\_lib.erl"},{line,227}]}]},{gen\_server,call,[riak\_core\_capability,{register,{riak\_core,vnode\_routing},{capability,[proxy,legacy],...}},...]}}
> in application\_master:init/4 line 138
> > 2013-04-24 04:05:15.531 [info] <0.7.0> Application riak\_core exited with
> reason: {{function\_clause,[{orddict,fetch,[riak@in
> ,[]],[{file,"orddict.erl"},{line,72}]},{riak\_core\_capability,renegotiate\_capabilities,1,[{file,"src/riak\_core\_capability.erl"},{line,415}]},{riak\_core\_capability,handle\_call,3,[{file,"src/riak\_core\_capability.erl"},{line,208}]},{gen\_server,handle\_msg,5,[{file,"gen\_server.erl"},{line,588}]},{proc\_lib,init\_p\_do\_apply,3,[{file,"proc\_lib.erl"},{line,227}]}]},{gen\_server,call,[riak\_core\_capability,{register,{riak\_core,vnode\_routing},{capability,[proxy,legacy],...}},...]}}
> >
> > Any ideas?
> >
> > Chris
> > \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
> > riak-users mailing list
> > riak-users@lists.basho.com
> > http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com
>
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com

