---
title: "Re: Short read error on .store() with protobufs using Python client"
description: ""
project: community
lastmod: 2011-01-21T14:43:20-08:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg02045"
mailinglist_parent_id: "msg02047"
author_name: "Bob Feldbauer"
project_section: "mailinglistitem"
sent_date: 2011-01-21T14:43:20-08:00
---


Interesting. I was actually seeing this all the time, not just 
intermittently. Removing the lines as described in bug #695 
(https://issues.basho.com/show\\_bug.cgi?id=695) did resolve my issue. 
Thanks for the help, Gary.


- Bob

On 1/21/2011 2:28 PM, Gary Flake wrote:

I had the same problem the other day and someone answered with the
fix. So search the archives on my name to find the precise answer.
But the fix was to remove the three lines in pbc.py where the check
and error message occur. Basically this is a known issue and the
check should not be there.

-- GWF

(sent from my cell phone.)

On Jan 21, 2011, at 1:48 PM, Bob Feldbauer wrote:


Thanks for the suggestion, Jon. This is occurring every time I try to do 
.store() via protobuf transport in the Python client (so yes, it is 
reproducible); however, there is no output in logs or riak console.

- Bob

On 1/21/2011 1:02 PM, Jon Meredith wrote:

Hi Bob,

That sounds like the connection got closed as the client was readying.

Have you checked through the server logs to verify that no processes died or no 
other nodes went down? Or if it's reproducible you should be able to start the 
server with 'riak console' and see what gets printed.

Cheers, Jon.
Basho Technologies


On Fri, Jan 21, 2011 at 11:36 AM, Bob 
Feldbauer&gt; wrote:

 I'm using the riak-python-client with Riak 0.14. If I use HTTP
 instead of PBC, my code works fine; however, with PBC I get a
 "socket returned short read" error. Any help would be appreciated!
 Code as follows (for debugging, I added .is\\_alive() which returns
 as expected, prior to the error being displayed):

 client = riak.RiakClient(host='servername', port=8087,
 transport\\_class=riak.RiakPbcTransport)
 riakBucket = client.bucket('bucketname')
 print client.is\\_alive()
 ... [code to setup the key/data] ...
 doc = riakBucket.new(key, data=result)
 doc.store()

 And the full error shown:

 Traceback (most recent call last):
 File "riak\\_import-pb.py", line 23, in
 doc.store()
 File
 "/usr/local/lib/python2.6/dist-packages/riak/riak\\_object.py", line
 269, in store
 Result = t.put(self, w, dw, return\\_body)
 File
 "/usr/local/lib/python2.6/dist-packages/riak/transports/pbc.py",
 line 190, in put
 msg\\_code, resp = self.recv\\_msg()
 File
 "/usr/local/lib/python2.6/dist-packages/riak/transports/pbc.py",
 line 349, in recv\\_msg
 self.recv\\_pkt()
 File
 "/usr/local/lib/python2.6/dist-packages/riak/transports/pbc.py",
 line 399, in recv\\_pkt
 format(len(recv\\_buf), want\\_len))
 riak.RiakError: 'Socket returned short read 1444 - expected 8192'


 - Bob Feldbauer

 \\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_
 riak-users mailing list
 riak-users@lists.basho.com
 http://lists.basho.com/mailman/listinfo/riak-users\\_lists.basho.com
