---
title: "Riak Search Unicode / String TypeError (Python client)"
description: ""
project: community
lastmod: 2011-04-04T08:17:52-07:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg02872"
author_name: "Mike Stoddart"
project_section: "mailinglistitem"
sent_date: 2011-04-04T08:17:52-07:00
---


I wrote a simple Python client to insert data but when I try to
perform a query, I get:

Traceback (most recent call last):
 File "./search.py", line 29, in 
 row = result.get()
 File "build/bdist.linux-x86\\_64/egg/riak/mapreduce.py", line 302, in get
 File "build/bdist.linux-x86\\_64/egg/riak/bucket.py", line 245, in get
 File "build/bdist.linux-x86\\_64/egg/riak/riak\\_object.py", line 290, in reload
 File "build/bdist.linux-x86\\_64/egg/riak/transports/pbc.py", line 152, in get
 File "build/bdist.macosx-10.6-universal/egg/google/protobuf/reflection.py",
line 510, in setter
 File 
"build/bdist.macosx-10.6-universal/egg/google/protobuf/internal/type\\_checkers.py",
line 91, in CheckValue
TypeError: u'events' has type , but expected one of:
(,)

My query is:

search\\_query = client.search('events', 'name:Fred')

Is it complaining about the bucket name? I had to manually build protobuf.

Thanks
Mike

\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\\_lists.basho.com

